version: "3.3"

services:
  dashboard:
    image: ghcr.io/vmgirls/probe-dashboard
    restart: always
    volumes:
      - ./data:/dashboard/data
    ports:
      - site_port:80
      - grpc_port:5555
